# -*- coding: utf-8 -*-
"""NumPy Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwMRmruY8siA0sN0-t1AzDWW08Q4G8bj
"""

import numpy as np

a = np.array([1, 2, 3])
b = np.array([[22, 34, 16], [4, 9, 10]])

print(a)
print(b)

z = np.zeros((3,4))
o = np.ones((3,4))
r = np.random.rand(3,4)
i = np.eye(3) # identity

print(z)
print(o)
print(r)
print(i)

# attribute / properties
print(a.shape)
print(b.shape)
print(a.ndim)
print(b.ndim)
print(a.size)
print(b.size)
print(a.dtype)
print(b.dtype)

# slicing & indexing

nums = [12, 33, 44, 17, 46, 18, 12]

print(nums[3]) # 17
print(nums[-1]) # 12
print(nums[-2]) # 18

print(nums[2:5])

print(b[1,1])
print(b[1,:])
print(b[:,1])

x = np.array([4, 5, 9])
y = np.array([1, 2, 4])

sum = x + y
print(sum)

mult = x * y
print(mult)

sq = x**2
print(sq)

print(x + 11)

print(np.vstack([x,y]))
print(np.hstack([x,y]))

mat1 = np.hstack([x,y])

print(np.mean(mat1))
print(np.median(mat1))
print(np.std(mat1))
print(np.min(mat1))
print(np.max(mat1))

print(b)
print(b.flatten())

mat = np.arange(16).reshape(4,4)
print(mat)

