# -*- coding: utf-8 -*-
"""Pandas Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VvJR7eveKI5BiNmqhKDpIeAXG-uACssb
"""

import pandas as pd

s1 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

print(s1)

print(s1['c'])

students_data = {
    'Name' : ["Adeen", "Rimsha", "Ahmed"],
    "Age" : [21, 23, 24],
    "Score": [75, 85, 65]
}

students_df = pd.DataFrame(students_data)

print(students_df)

print(students_df['Name'])

print(students_df.loc[2])

df = pd.read_excel('/content/2 - sample-data-10mins.xlsx')

print(df.head(2))

print(df.tail(2))

