# -*- coding: utf-8 -*-
"""Python Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125pn9WFbKn7er8cs9XfMpOv1VQgqGehX
"""

print("Hello World")

a=20
print(type(a))

age=19

if age>18:
  print("You are an adult")
  print("This is also in if block")

print("This is outside if block")

num=-4

if num<0:
  print("-ve numbet")
elif num>0:
  print("+ve number")
else:
  print("zero or invalid")

# short hand

num1 = 88

print("Even") if num1%2==0 else print("Odd")

def greet(name):
  print("================")
  print(" Welcome " + name)
  print("================")

greet("Maaz")
greet("Ahmed")
greet("Adeen")

i=55
while i > 4:
  print("num is : " + str(i) )
  i -= 5

def generateTable(num):
  i=1
  while i<=10:
    print(str(num) + " x " + str(i) + " = " + str(num*i))
    i+=1

generateTable(13)

generateTable(155)

students = ["Ali", "Ahmed", "Sarah"]

for s in students:
  print("My name is " + s)

for x in range(7):
  print("The number is " + str(x))

for x in range(2,7):
  print("The number is " + str(x))

for x in range(2,7,3):
  print("The number is " + str(x))

for x in range(2,7,3):
  print("The number is " + str(x))
else:
  print("loop ended")

